# Generated by Django 6.0.2 on 2026-02-28 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_title', models.CharField()),
                ('company', models.CharField()),
                ('url', models.URLField()),
                ('job_description', models.TextField()),
                ('notes', models.TextField()),
                ('status', models.CharField(choices=[('SAVED', 'saved'), ('APPLIED', 'applied'), ('DENIED', 'denied'), ('INTERVIEWING', 'interviewing'), ('UNDER REVIEW', 'under review'), ('RECEIVED OFFER', 'received offer')])),
                ('date_applied', models.DateTimeField(blank=True, null=True)),
                ('next_step_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
